frontendPolicies:
  accessLog:
    add:
      user: request.headers["user-agent"]

llm:
  policies:
    jwtAuth:
      issuer: agentgateway.dev
      audiences: [test.agentgateway.dev]
      jwks: '{"keys":[{"use":"sig","kty":"EC","kid":"XhO06x8JjWH1wwkWkyeEUxsooGEWoEdidEpwyd_hmuI","crv":"P-256","alg":"ES256","x":"XZHF8Em5LbpqfgewAalpSEH4Ka2I2xjcxxUt2j6-lCo","y":"g3DFz45A7EOUMgmsNXatrXw1t-PG5xsbkxUs851RxSE"}]}'
    authorization:
      rules:
      - 'jwt.email.endsWith("@example.com")'
  models:
  - name: claude-3-haiku
    provider: anthropic
    params:
      model: claude-3-5-haiku-20241022
      apiKey: "sk-123"
    matches:
    - headers:
      - name: "X-Org"
        value:
          exact: "engineering"
  - name: gemini-0.5-pro
    provider: vertex
    params:
      model: claude-3-5-haiku-20241022
      apiKey: "sk-123"
      vertexRegion: global
      vertexProject: my-vertex-project
  - name: gpt-7-max
    provider: azureOpenAI
    params:
      model: gpt-3.5-turbo
      azureHost: my-azure-openai-endpoint.openai.azure.com
      azureApiVersion: v1
  - name: gpt-3.5-turbo
    provider: openAI
